site_name: kulprit
repo_url: https://github.com/yannmclatchie/kulprit

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Overview: 'index.md'
  - Tutorials:
    - Introduction: notebooks/tutorials/projpred.ipynb
  - Quick start: notebooks/quick-start.ipynb
  - api_docs.md
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: true
      watch:
        - src/kulprit
  - mknotebooks

copyright: Copyright &copy; 2022 Yann McLatchie

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yannmclatchie/kulprit
      name: kulprit on GitHub
