site_name: kulprit
repo_url: https://github.com/yannmclatchie/kulprit

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Overview: 'index.md'
  - Tutorials:
    - Introduction: notebooks/tutorials/projpred.ipynb
  - Quick start: notebooks/quick-start.ipynb
  - api_docs.md
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/extra.js

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: true
      watch:
        - src/kulprit
  - mknotebooks
