[tool.poetry]
name = "pyprojpred"
version = "0.1.0"
description = "Projection predictive variable selection"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.7.1"
jupyter = "*"
numpy = "^1.19.5"
pandas = "^1.3.1"
matplotlib = "^3.1.2"
seaborn = "^0.11.2"
numpyro = "0.7.2"
arviz = "^0.11.2"
scikit-learn = "^0.22"
torch = "^1.10.1"
jax = "0.2.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
