[tool.poetry]
name = "kulprit"
version = "0.1.0"
description = "Kullback-Leibler projection predictive variable selection"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
arviz = "^0.11.2"
autograd = "1.3"
bambi = "0.7.1"
jupyter = "1.0.0"
keras = "2.8.0"
numba = "0.51.2"
numpy = "^1.21.5"
pandas = "^1.3.5"
pip = "^22.0.3"
pymc3 = "3.11.4"
python = "3.7.2"
seaborn = "0.11.2"
scipy = "1.7.3"
statsmodels = "0.10.2"
Theano-PyMC = "1.1.2"
torch = "^1.10.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
