[tool.poetry]
name = "kulprit"
version = "0.0.1"
description = "Kullback-Leibler projections for Bayesian model selection in Generalised Linear Models"
authors = [
    "Yann McLatchie <Your email address (eq. you@example.com)>",
]
license = "MIT"
readme = "README.md"

documentation = "https://yannmclatchie.github.io/kulprit"
homepage = "https://yannmclatchie.github.io/kulprit"
repository = "https://github.com/yannmclatchie/kulprit"

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

packages = [
    { include = "kulprit", from = "src" }
]

[tool.poetry.dependencies]
arviz = "^0.11.2"
bambi = "0.7.1"
jupyter = "1.0.0"
numpy = "^1.21.5"
pandas = "^1.3.5"
pip = "^22.0.3"
pymc3 = "3.11.4"
python = ">=3.7.2, <3.10"
scipy = "1.7.3"
statsmodels = "0.10.2"
Theano-PyMC = "1.1.2"
torch = "^1.10.0"

[tool.poetry.dev-dependencies]
autoflake = "*"
black = "*"
flake8 = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-eradicate = "*"
flake8-logging-format = "*"
isort = "*"
mkdocstrings = "*"
mkdocs-material = "*"
mypy = "*"
pep8-naming = "*"
pre-commit = "*"
pymdown-extensions = "*"
pytest = "*"
pytest-cov = "*"
python-kacl = "*"
pyupgrade = "*"
tryceratops = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.black]
target-version = ["py37"]
include = '\.pyi?$'

[tool.pytest.ini_options]
addopts = """\
    --cov kulprit \
    --cov tests \
    --cov-report term-missing \
    --no-cov-on-fail \
"""

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover'
]

[tool.mypy]
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
check_untyped_defs = true
show_error_codes = true
